package anlf

















































}	fmt.Printf("  Match: %v\n", (extIPHost & mask) == ueSubnet)	fmt.Printf("  Expected subnet: 0x%08x\n", ueSubnet)	fmt.Printf("  Ext IP & mask: 0x%08x\n", extIPHost & mask)		fmt.Printf("\n")	fmt.Printf("  Match: %v\n", (ueIPHost & mask) == ueSubnet)	fmt.Printf("  Expected subnet: 0x%08x\n", ueSubnet)	fmt.Printf("  UE IP & mask: 0x%08x\n", ueIPHost & mask)	fmt.Printf("Subnet match test (after bpf_ntohl):\n")		ueSubnet := uint32(0x0a3c0000)	mask := uint32(0xffff0000)	// Apply /16 mask in host byte order		fmt.Printf("\n")	fmt.Printf("  Host byte order (Little-endian): 0x%08x\n", extIPHost)	fmt.Printf("  Network byte order (Big-endian): 0x%08x\n", extIPNet)	fmt.Printf("External IP: %s\n", extIP)		fmt.Printf("\n")	fmt.Printf("  Host byte order (Little-endian): 0x%08x\n", ueIPHost)	fmt.Printf("  Network byte order (Big-endian): 0x%08x\n", ueIPNet)	fmt.Printf("UE IP: %s\n", ueIP)		extIPHost := binary.LittleEndian.Uint32(extIPBytes)	ueIPHost := binary.LittleEndian.Uint32(ueIPBytes)	// In host byte order (little-endian on x86)		extIPNet := binary.BigEndian.Uint32(extIPBytes)	ueIPNet := binary.BigEndian.Uint32(ueIPBytes)	// Convert to uint32 (network byte order first, then convert to host)		extIPBytes := net.ParseIP(extIP).To4()	ueIPBytes := net.ParseIP(ueIP).To4()	// Parse IPs		extIP := "10.201.66.231"	ueIP := "10.60.100.1"	// Test IPsfunc main() {)	"net"	"fmt"	"encoding/binary"import (package main